controllers/album.py
from flask import *
from extensions import *
from config import *
from hashlib import md5
from os import *


album = Blueprint('album', __name__, template_folder='templates')


UPLOAD_FOLDER = 'static/images/images'
ALLOWED_EXTENSIONS = set(['png', 'jpg', 'bmp', 'gif'])


def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS


@album.route('/album/edit', methods=['GET', 'POST'])
def album_edit_route():

	firstname = ""
	lastname = ""
	db = connect_to_database()
	cur = db.cursor()

	if request.method == 'GET':
		albumid = request.args.get('albumid')

		cur.execute("SELECT title FROM Album WHERE albumID = %s", [albumid])
		title = cur.fetchall()
		if not title:
			return render_template('404.html'), 404

		if 'username' in session:
			cur.execute("SELECT * FROM Album WHERE albumID=%s AND username=%s", (albumid, session['username']))
			if not cur.fetchall():
				return render_template('403.html'), 403
		else:
			return redirect(url_for('log.login_route'))

	if request.method == 'POST':
		albumid = request.form.get('albumid')

		cur.execute("SELECT title FROM Album WHERE albumID = %s", [albumid])
		title = cur.fetchall()
		if not title:
			return render_template('404.html'), 404

		if 'username' in session:
			cur.execute("SELECT * FROM Album WHERE albumID=%s AND username=%s", (albumid, session['username']))
			if not cur.fetchall():
				return render_template('403.html'), 403
		else:
			return redirect(url_for('log.login_route'))

		if request.form.get('op') == 'add':
			file = request.files['file']

			if file.filename == '':
				flash('No selected file')
				return redirect(request.url)


			if file and allowed_file(file.filename):

				m = md5()
				m.update(str(albumid))
				m.update(file.filename)
				picid = m.hexdigest()
				format = file.filename.rsplit('.', 1)[1]
				filename = picid + "." + format 

				file.save(path.join(UPLOAD_FOLDER, filename))
				cur.execute("SELECT MAX(sequenceNum) FROM Contain")
				sequenceNum = cur.fetchall()
				sequenceNum = sequenceNum[0]['MAX(sequenceNum)']
				sequenceNum += 1
				cur.execute("INSERT INTO Photo (picID, format) VALUES (%s, %s)", (picid, format ))
				cur.execute("INSERT INTO Contain (sequenceNum, albumID, picID, caption) VALUES (%s, %s, %s, %s)", (sequenceNum, albumid, picid, ""))
				cur.execute("UPDATE Album SET lastUpdate=CURRENT_TIMESTAMP() WHERE albumID=%s", albumid)

		if request.form.get('op') == 'delete':
			picid = request.form.get('picid')
			cur.execute("SELECT format FROM Photo WHERE picID=%s", [picid])
			badPic = cur.fetchall()
			format = badPic[0]['format']
			location = "static/images/images/" + picid + "." + format
			remove(path.join(getcwd(), location))
			cur.execute("DELETE FROM Contain WHERE picID=%s", [picid])
			cur.execute("DELETE FROM Photo WHERE picID = %s", [picid])
			cur.execute("UPDATE Album SET lastUpdate=CURRENT_TIMESTAMP() WHERE albumID=%s", albumid)

		if request.form.get('op') == 'grant':
			username = request.form.get('username')
			cur.execute('INSERT INTO AlbumAccess(albumID, username) VALUES (%s, %s)', (albumid, username))

		if request.form.get('op') == 'revoke':
			username = request.form.get('username')
			cur.execute('DELETE FROM AlbumAccess WHERE username=%s AND albumID=%s', (username, albumid))

		if request.form.get('op') == 'access':
			access = request.form.get('access')
			cur.execute("UPDATE Album SET access=%s WHERE albumID=%s", (access, albumid))
			cur.execute("UPDATE Album SET lastUpdate=CURRENT_TIMESTAMP() WHERE albumID=%s", [albumid])
			if access == 'public':
				cur.execute("DELETE FROM AlbumAccess WHERE albumID=%s", [albumid])


	
	cur.execute('SELECT access FROM Album WHERE albumID=%s AND access=%s', (albumid, 'private'))
	private = cur.fetchall()
	cur.execute('SELECT username FROM AlbumAccess WHERE albumID=%s', [albumid])
	access = cur.fetchall()
	cur.execute("SELECT Contain.picID, Photo.format FROM Contain JOIN Photo WHERE Contain.picid = Photo.picid AND Contain.albumID = %s", [albumid])
	pics = cur.fetchall()
	cur.execute('SELECT firstname, lastname FROM User WHERE username=%s', [session['username']])
	name = cur.fetchall()
	firstname = name[0]['firstname']
	lastname = name[0]['lastname']



	options = {
		"edit": True,
		"pics": pics,
		"albumid": albumid,
		"title": title,
		"access": access,
		"inSession": True,
		"firstname": firstname,
		"lastname": lastname,
		"private": private
	}
	return render_template("album.html", **options)

@album.route('/album', methods=['GET','POST'])
def album_route():

	return render_template("single_page.html")

controllers/albums.py
from flask import *
from extensions import *
from config import *
from os import *

albums = Blueprint('albums', __name__, template_folder='templates')

@albums.route('/albums/edit', methods = ['GET', 'POST'])
def albums_edit_route():
	firstname = ""
	lastname = ""
	db = connect_to_database()
	cur = db.cursor()
		
	if not 'username' in session:
		return redirect(url_for('log.login_route'))

	#check for username args
	user = session['username']


	if request.method == 'POST':

		if request.form.get('op') == 'delete':
			albumID = request.form.get('albumid')
			cur.execute("SELECT picID from Contain WHERE albumID=%s", [albumID])
			badPics = cur.fetchall()
			for x in badPics:
				picid = x['picID']
				cur.execute("SELECT format from Photo where picID = %s", [picid])
				format = cur.fetchall()
				format = format[0]['format']
				location = "static/images/images/" + picid + "." + format
				remove(path.join(getcwd(), location))
				print location, "deleted"
				cur.execute("DELETE FROM Contain WHERE picID=%s", [picid])
  				cur.execute("DELETE FROM Photo WHERE picID = %s", [picid])
		
			cur.execute("DELETE FROM Album WHERE albumID=%s", [albumID])
			cur.execute("DELETE FROM AlbumAccess WHERE albumID=%s", [albumID])

		
		if request.form.get('op') == 'add':
			user = request.form.get('username')
			newAlbum = request.form.get('title')
			access = 'private'
			cur.execute("INSERT INTO Album (title, username, access) VALUES (%s, %s, %s)", ([newAlbum], [user], access))


	cur.execute('SELECT firstname, lastname FROM User WHERE username=%s', [user])
	name = cur.fetchall()
	firstname = name[0]['firstname']
	lastname = name[0]['lastname']

	cur.execute("SELECT title, albumID FROM Album WHERE username = %s", [user])
	albumTitles = cur.fetchall()


	options = {
		"edit": True,
		"albumTitles": albumTitles,
		"user": user,
		"inSession": True,
		"owner": True,
		"firstname": firstname,
		"lastname": lastname
	}
	return render_template("albums.html", **options)


@albums.route('/albums', methods = ['GET','POST'])
def albums_route():

	db = connect_to_database()
	cur = db.cursor()

	firstname = ""
	lastname = ""
	owner = False
	if request.args.get('username'):
		inSession = False
		if 'username' in session:
			inSession = True
		user = request.args.get('username')
		cur.execute("SELECT title, albumID FROM Album WHERE username = %s AND access=%s", ([user], 'public'))
		albumTitles = cur.fetchall()
		if not albumTitles:
			return render_template('404.html'), 404
	else:
		cur.execute('SELECT firstname, lastname FROM User WHERE username=%s', [session['username']])
		name = cur.fetchall()
		firstname = name[0]['firstname']
		lastname = name[0]['lastname']
		user = session['username']
		owner = True
		inSession = True
		cur.execute("SELECT title, albumID FROM Album WHERE username = %s", [user])
		albumTitles = cur.fetchall()


	options = {
		"edit": False,
		"albumTitles": albumTitles,
		"user": user,
		"inSession": inSession,
		"owner" : owner,
		"firstname": firstname,
		"lastname": lastname
	}
	return render_template("albums.html", **options)

controllers/log.py
from flask import *
from extensions import *


log = Blueprint('log', __name__, template_folder='templates')

@log.route('/login', methods=['GET', 'POST'])
def login_route():
	
	if 'username' in session:
		return redirect(url_for('user.user_edit_route'))

	return render_template("log.html")

'''@log.route('/logout', methods=['GET', 'POST'])
def logout_route():
	if request.method == 'POST':
		session.pop('username', None)
		return redirect(url_for('main.test_route'))'''

controllers/pic.py
from flask import *
from extensions import *
from config import *
from hashlib import md5
from os import *


pic = Blueprint('pic', __name__, template_folder='templates')

@pic.route('/pic', methods=['GET', 'POST'])
def pic_route():

	return render_template("single_page.html")

controllers/user.py
from flask import *
from extensions import *
import hashlib
import uuid
import re

user = Blueprint('user', __name__, template_folder='templates')

@user.route('/user/edit', methods=['GET', 'POST'])
def user_edit_route():

	if 'username' not in session:
		return redirect(url_for('log.login_route'))
	else:
		return render_template('user.html')


@user.route('/user', methods=['GET', 'POST'])
def user_route():

	if 'username' in session:

		return redirect(url_for('user.user_edit_route'))

	return render_template('user.html')

templates/album.html
{% extends "base.html" %}
{% block content %}


	<div id="content"></div>

	{%if inSession%}
		<h1>Logged in as {{firstname}} {{lastname}}</h1>
		<a href={{url_for('main.test_route')}} id="nav_home">Nav Home</a><br>
		<a href={{url_for('user.user_edit_route')}} id='nav_edit')>Edit Account</a><br>
		<a href={{url_for('albums.albums_route')}} id="nav_albums">My Albums</a><br>
    <form action={{url_for('log.logout_route')}} method='POST' id="nav_logout">
      	<input type="submit" value="Logout" id="nav_logout">
      </form>
	{%endif%}

	  {%if 'username' not in session %}
        <a href= {{url_for('log.login_route')}} id="home_login">Log in</a><br>
      {% endif %}


	{%for x in title%}
		<h1>{{x['title']}}</h1>
	{%endfor%}

	{% if not edit %}

	    {%for pic in pics%}
	    	<a href={{url_for('pic.pic_route', picid=pic.picID)}} id="pic_{{pic.picID}}_link"><img src="/static/images/images/{{pic['picID']}}.{{pic.format}}" style="width:210px;height:210px;"></a><br/>
	    	{{pic['posted']}}<br>
	    	{{pic['caption']}}<br><br>
	    {% endfor %}

	    {% if owner %}
			<a href={{url_for('album.album_edit_route',albumid=albumid)}}>Edit Album</a>
		{%endif%}

	{% endif %}

    {% if edit %}

    	<form action={{url_for('album.album_edit_route')}} method='POST'>
    		<input type="hidden" name="op" value="access">
    		<input type="hidden" name="albumid" value="{{albumid}}">
    		<input type="radio" name="access" value="public" id="album_edit_public_radio">Public<br />
    		<input type="radio" name="access" value="private" id="album_edit_private_radio">
    		Private<br />
    		<input type="submit" value="Submit" id="album_edit_access_submit">
    	</form>

    	{%if private%}
    	<table>
    		<tr><th>Username</th><th>Update Access</th></tr>
    		{%for user in access%}
    			<tr><td>{{user['username']}}</td>
    				<td><form action={{url_for('album.album_edit_route')}} method='POST'>
    					<input type="hidden" name="op" value="revoke">
    					<input type="hidden" name="albumid" value={{albumid}}>
    					<input type="hidden" name="username" value={{user['username']}}>
    					<input type="submit" value="Revoke" id="album_edit_revoke_{{user['username']}}">
    				</form></td>
    		{%endfor%}
    		<tr><td>Add access to user
			<tr><td><form action={{url_for('album.album_edit_route')}} method='POST'>
					<input type="hidden" name="op" value="grant">
					<input type="hidden" name="albumid" value={{albumid}}>
					<input type="text" name="username" value=""id="album_edit_grant_input">
					<input type="submit" value="Add" id="album_edit_grant_submit">
				</form></td>
    		</td>
    	</table>
    	{%endif%}

    	{%for pic in pics%}
    		<table>
	          <tr>
			    <td><a href={{url_for('pic.pic_route', picid=pic.picID)}} id="pic_{{pic.picID}}_link"><img src="/static/images/images/{{pic.picID}}.{{pic.format}}" style="width:210px;height:210px;"></a>
			    <td>
			    	<form action={{url_for('album.album_edit_route')}} method='POST'>
			    		<input type="hidden" name="op" value="delete">
			    		<input type="hidden" name="picid" value="{{pic.picID}}">
			    		<input type="hidden" name="albumid" value="{{albumid}}">
			    		<input type="submit" value="Delete" id="delete_pic_{{pic.picID}}">
			    	</form>
			    </td>
			</table>
		{% endfor %}
		<table>
          <tr>
		    <td><b>Add a new photo</b></td>
		    <td>
		    	<form action={{url_for('album.album_edit_route')}} enctype="multipart/form-data" method='POST' id = >
		    		<input type="hidden" name="op" value="add">
		    		<input type="hidden" name="albumid" value="{{albumid}}">
		    		<input type="file" name="file" id="file_input">
		    		<input type="submit" name="Submit" id="file_submit">
		    	</form>
		    </td>
		</table>
    {% endif %}
{% endblock %}

templates/albums.html
{% extends "base.html" %}
{% block content %}

	{%if inSession%}
		<h1>Logged in as {{firstname}} {{lastname}}</h1>
		<a href={{url_for('main.test_route')}} id="nav_home">Nav Home</a><br>
		<a href={{url_for('user.user_edit_route')}} id='nav_edit')>Edit Account</a><br>
		<a href={{url_for('albums.albums_route')}} id="nav_albums">My Albums</a><br>
      <form action={{url_for('log.logout_route')}} method='POST' id="nav_logout">
      	<input type="submit" value="Logout" id="nav_logout">
      </form>
	{%endif%}

     {%if 'username' not in session %}
        <a href= {{url_for('log.login_route')}} id="home_login">Log in</a><br>
      {% endif %}


    <h1>ALBUMS</h1>

    {% if not edit %}

	    {%for album in albumTitles%}

	    	<h3><a href={{url_for('album.album_route',albumid=album.albumID)}} id="album_{{album.albumID}}_link">{{album['title']}}</a></h3>
	    {% endfor %}

	    {%if owner%}
	    	<h3><a href={{url_for('albums.albums_edit_route')}} id="user_albums_edit_{{user}}">Edit Albums</a></h3>
	    {%endif%}

	{%endif%}

    {% if edit %}
    	{%for album in albumTitles%}
	        <table>
	          <tr>
			    <td><b>{{album['title']}}</b></td>
			    <td>
			    	<a href={{url_for('album.album_edit_route',albumid=album.albumID)}} id="album_edit_{{album.albumID}}_link">Edit</a>
			    </td>
			    <td>
			    	<form action={{url_for('albums.albums_edit_route')}} method='POST' id="delete_album_{{album.albumID}}">
			    		<input type="hidden" name="op" value="delete">
			    		<input type="hidden" name="albumid" value="{{album.albumID}}">
			    		<input type="submit" value="Delete">
			    	</form>
			 	</td>

			  </tr><tr></tr>
			</table>
		{% endfor %}
		<table>
		  <tr>
		    <td><b>Add new album</b></td>
		    <td>
		    	<form action={{url_for('albums.albums_edit_route')}} method='POST'>
		    		<input type="hidden" name="op" value="add">
		    		<input type="hidden" name="username" value="{{user}}" >
		    		<input type="text" name="title" value="" id="album_add_name">	
		    		<input type="submit" value="Add" id="album_add_submit">
		    	</form>
		    </td>
		</table>
    {% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>

    <link rel="stylesheet" href="/static/css/style.css" />
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <title>EECS485</title>
</head>
<body>
  <div class="center">
  	{% block content %}{% endblock %}

  </div>


  <script type="text/javascript" src="/static/js/main.js"></script>





</body>

</html>

templates/index.html
{% extends "base.html" %}
{% block content %}


	<meta name="description" content="Photo Album">
	<meta name="author" content="Ryan Pifer">

    <title>Photo Album</title>


    <p class="left">
      	<h1>Welcome to our Photo Album!</h1>

      {%if 'username' in session %}
        <h1>Logged in as {{firstname}} {{lastname}}</h1>
        <a href={{url_for('main.test_route')}} id="nav_home">Nav Home</a><br>
        <a href={{url_for('user.user_edit_route')}} id='nav_edit')>Edit Account</a><br>
        <a href={{url_for('albums.albums_route')}} id="nav_albums">My Albums</a><br>
          <form id="nav_logout">
            <input type="submit" value="Logout">
          </form>
      {% endif %}

      {%if 'username' not in session %}

        <a href={{url_for('user.user_route')}} id="home_user_create">Create Account</a><br>
        <a href= {{url_for('log.login_route')}} id="home_login">Log in</a><br>
      

        {%for user in users%}
          <a href={{url_for('albums.albums_route', username=user['username'])}}>{{user['username']}}</a><br>
        {%endfor%}
      {%endif%}

  		{% for album in albums %}
      <body>
			 <h3><a href={{url_for('album.album_route', albumid=album['albumid'])}} id="album_{{album['albumid']}}_link">{{album['title']}}</a></h3>
      </body>
  		{% endfor %}

      	<footer>Authored: Ryan Pifer, Semptember 2016</footer>
    </p>
{% endblock %}

templates/log.html
{% extends "base.html" %}
{% block content %}
	<p class="center">
		{% for error in message%}
			<p class="error">
  				{{error}}
			</p>
		{%endfor%}
		<h1>Log In</h1><br>
		<form id="submitLogin">
			Username:
			<input type="text" name="username" value="" id="login_username_input"><br>
			Password:
			<input type="password" name="password" value="" id="login_password_input"><br>
			<input type="submit" value="Submit" id="login_submit">
		</form>
	</p>

	 <script type="text/javascript" src="/static/js/log.js"></script>

{% endblock %}

templates/pic.html
{% extends "base.html" %}
{% block content %}

	{%if inSession%}
		<h1>Logged in as {{firstname}} {{lastname}}</h1>
		<a href={{url_for('main.test_route')}} id="nav_home">Nav Home</a><br>
		<a href={{url_for('user.user_edit_route')}} id='nav_edit')>Edit Account</a><br>
		<a href={{url_for('albums.albums_route')}} id="nav_albums">My Albums</a><br>
      <form action={{url_for('log.logout_route')}} method='POST' id="nav_logout">
      	<input type="submit" value="Logout" id="nav_logout">
      </form>
	{%endif%}


    <h1>PIC</h1>
    <img src="/static/images/images/{{picid}}.{{format['format']}}"><br/>

    <p id="pic_{{picid}}_caption">{{format['caption']}}</p>
    {%if owner%}
    	Edit caption<br>
   		<form action={{url_for('pic.pic_route', picid=picid)}} method='POST'>
    		<input type="hidden" name="op" value="caption">
    		<input type="hidden" name="picid" value="{{picid}}">
    		<input type="text" name="caption" value="" id="pic_caption_input">
    		<input type="submit" value="Submit" id="pic_caption_submit">
    	</form>
    {%endif%}
    {%if not isFirst%}
    	<a href={{url_for('pic.pic_route', picid=previd)}} id="prev_pic">Previous&nbsp;</a>
    {%endif%}

	<a href={{url_for('album.album_route', albumid=albumid)}} id="parent_album">Return to Album&nbsp;</a>

    {%if not isLast%}
    	<a href={{url_for('pic.pic_route', picid=nextid)}} id="next_pic">Next</a>
    {%endif%}


{% endblock %}

templates/single_page.html
{% extends "base.html" %}
{% block content %}

     {%if 'username' not in session %}
        <a href= {{url_for('log.login_route')}} id="home_login">Log in</a><br>
      {% endif %}

	<div id="content"></div>

 	<script type="text/javascript" src="/static/js/single_page.js"></script>
{% endblock %}

templates/user.html
{% extends "base.html" %}
{% block content %}

	<meta name="author" content="Ryan Pifer">

  {%for error in message%}
    <p class="error">
      {{error}}
    </p>
  {%endfor%}

  {%if not session.logged_in %}
    <p class="center">
      	<h1>Create an Account</h1><br>
          <p>
  		      <form id="createUser">
              Username:<br>
             <input type="text" name="username" value="" id="new_username_input"><br>
             First Name:<br>
              <input type="text" name="firstname" value="" id="new_firstname_input"><br>
              Last Name:<br>
              <input type="text" name="lastname" value="" id="new_lastname_input"><br>
              Password:<br>
              <input type="password" name="password1" value="" id="new_password1_input"><br>
              Re-enter Password:<br>
              <input type="password" name="password2" value="" id="new_password2_input"><br>
              Email:<br>
              <input type="text" name="email" value="" id="new_email_input"><br>
              <input type="submit" value="Submit" id="new_submit"><br>
            </form>
          </p>
    {%endif%}

    {% if session.logged_in %}
      <h1>Edit Account Information</h1><br>
        <p>
          Change First Name
          <form id="updateUser">
            <input type="text" name="firstname" value="" id="update_firstname_input">
          Change Last Name
            <input type="text" name="lastname" value="" id="update_lastname_input">
          Change Password
            <input type="password" name="password1" value="" id="update_password1_input"><br>
          Re-type Password<br>
            <input type="password" name="password2" value="" id="update_password2_input">
          Change E-mail
            <input type="text" name="email" value="" id="update_email_input">
            <input type="submit" value="Submit" id="update_submit">
          </form>
    {%endif%}


      	<footer>Authored: Ryan Pifer, Semptember 2016</footer>
    </p>

    <script type="text/javascript" src="/static/js/user.js"></script>
{% endblock %}